### PR TITLE
Add support for schedule event

### PR DESCRIPTION
**Pull request by cbartz**
Applicable spec: n/a

### Overview

The GitHub schedule event handling is added to the pre-job script and an additional end-to-end test is added. 
The [schedule event](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) can only be triggered on the main branch, so to implement the end-to-end test, another repo is dynamically created in `secrets.E2E_TESTING_TOKEN_ORG` and the schedule event tests are run there.

### Rationale

A self-hosted runner should handle the schedule event.

### Checklist

- [x] The [charm style guide](https://juju.is/docs/sdk/styleguide) was applied
- [x] The [contributing guide](https://github.com/canonical/is-charms-contributing-guide) was applied
- [x] The changes are compliant with [ISD054 - Managing Charm Complexity](https://discourse.charmhub.io/t/specification-isd014-managing-charm-complexity/11619)
- [x] The documentation is generated using `src-docs`
- [x] The documentation for charmhub is updated.
- [x] The PR is tagged with appropriate label (`urgent`, `trivial`, `complex`)

### CODE REVIEW

**Comment by cbartz** [comment]
@yhaliaw , could you please have a look if you are happy with the schedule test approach. This would currently mean that a schedule workflow would run every 5 minutes.
 We may need an additional cleanup mechanism (deleting old workflow runs that did not run the did not trigger the schedule event test job due to lack of corresponding end-to-end tests branches).
 
An alternative approach would be to test the main branch only once a day or so, but then we would not be immediately alerted when a pr breaks schedule event support, which may be fine as we do not immediately promote releases to stable.

**Review by jdkandersson — DISMISSED** [review]

**Comment by yhaliaw** [comment]
> @yhaliaw , could you please have a look if you are happy with the schedule test approach. This would currently mean that a schedule workflow would run every 5 minutes. We may need an additional cleanup mechanism (deleting old workflow runs that did not run the did not trigger the schedule event test job due to lack of corresponding end-to-end tests branches).
> 
> An alternative approach would be to test the main branch only once a day or so, but then we would not be immediately alerted when a pr breaks schedule event support, which may be fine as we do not immediately promote releases to stable.

A test every 5 mins seems quite frequent. Is there a reason for it? Would a test every hour cause any problems?

**Comment by cbartz** [comment]
> > @yhaliaw , could you please have a look if you are happy with the schedule test approach. This would currently mean that a schedule workflow would run every 5 minutes. We may need an additional cleanup mechanism (deleting old workflow runs that did not run the did not trigger the schedule event test job due to lack of corresponding end-to-end tests branches).
> > An alternative approach would be to test the main branch only once a day or so, but then we would not be immediately alerted when a pr breaks schedule event support, which may be fine as we do not immediately promote releases to stable.
> 
> A test every 5 mins seems quite frequent. Is there a reason for it? Would a test every hour cause any problems?

The end-to-end test (not included in this draft PR) triggered by a PR will have to wait for the schedule. So if we set it to one hour, the end-to-end test would take a very long time.

**Review by yhaliaw — DISMISSED** [review]
LGTM

**Comment by cbartz** [comment]
The end-to-end test is now implemented by using a different repo for the schedule test. The PR description has been updated.

**Review by jdkandersson — APPROVED** [review]

**Review by yhaliaw — APPROVED** [review]
LGTM

**Pull request merged**
