### PR TITLE
Install unzip and gh command functionality.

### PR DESCRIPTION
**Pull request by codethulu**
Applicable spec: N/A

### Overview

Include `gh` and `unzip` functionality from the Ubuntu Archives. Included some simple checks in the e2e test file, to ensure the packages have been installed correctly.

### Rationale

This functionality was not currently present, and has been requested as an addition.

### Juju Events Changes

Juju events should not be affected by this change.

### Module Changes

No changes to any module functionality.

### Library Changes

Charm libraries are unchanged.

### Checklist

- [x] The [charm style guide](https://juju.is/docs/sdk/styleguide) was applied
- [x] The [contributing guide](https://github.com/canonical/is-charms-contributing-guide) was applied
- [x] The changes are compliant with [ISD054 - Managing Charm Complexity](https://discourse.charmhub.io/t/specification-isd014-managing-charm-complexity/11619)
- [ ] The documentation is generated using `src-docs`
- [ ] The documentation for charmhub is updated.
- [x] The PR is tagged with appropriate label (`urgent`, `trivial`, `complex`)

This PR does not warrant any new charm documentation due to the nature of this change.

### CODE REVIEW

**Comment by codethulu** [comment]
Conclusion for https://github.com/canonical/github-runner-operator/pull/221
Due to force pushes being disabled, I was unable to push my rebase that fixed previously unverified commits. This new PR was the suggested solution.

**Review by cbartz — APPROVED** [review]
Can you close the other PR?

**Review by mthaddon — APPROVED** [review]

**Comment by codethulu** [comment]
Will close the other PR, was waiting for tests to pass here 👍

**Comment by jdkandersson** [comment]
What about a slightly different approach, could we install the current `gh` version without using our archives since it has a really old version in it and then create a `gh` PPA/ snap as a follow up? That way, users get the version they expect and we'll immediately begin working on fixing the issue of not using an `apt` package/ snap?

**Pull request merged**
